### ISSUE TITLE
Using user+organization flow (Both) - can't get data about the organization

### ISSUE THREAD

**Issue by avivday2** [auth0/auth0-vue#250] opened 2023-08-05 01:15 UTC
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the "Both" flow for personal accounts and organizations, no data about the current selected "org" or "personal account" is being attached, no way to know what the user chose.
Tried to add some info in Flows, but no luck as well.

### Reproduction

1. Choose "Both flow"
2. Check out user or idTokenClaims to see no data about org

### auth0-vue version

2.2.1

### Vue version

3.3.4

### Which browsers have you tested in?

Chrome

**Comment by ewanharris** [comment] 2023-08-08 16:00
Thanks for reaching out @avivday2!

When testing this against the [local playground in the repo](https://github.com/auth0/auth0-vue/tree/main/playground), I'm able to see the `org_id` claim in the payload when I select to authenticate using an organization, and it is not present when selecting a person account.

Are you able to reproduce this using either the [playground](https://github.com/auth0/auth0-vue/tree/main/playground) or the [vue sample](https://github.com/auth0-samples/auth0-vue-samples) with the same client id?

**Comment by avivday2** [comment] 2023-08-08 19:30
Hi @ewanharris thanks for answering!
Well, I can reproduce it on the vue sample when I use onBeforeMount in the App.vue and then I use 

`const accessToken = await auth0.getAccessTokenSilently();`

I do it in my app to save the access token, and attach it to the API calls.
So my api expecting an "Authorization" header with a Bearer token.

Is there a better way to achieve what I am trying to do?

In the sample app, there is no actions made to a protected API - so it never use the access token, tried to check cookies/localstorage and I can't seem to find it.

Can you help me please?
Thanks!

**Comment by avivday2** [comment] 2023-08-08 19:39
Quick update,
It shows the org,
but 
`const accessToken = await auth0.getAccessTokenSilently();`
returns with no org.
I checked the payload of the token - and it's without any org id.

**Comment by avivday2** [comment] 2023-08-08 19:53
Well, I found a solution. 
I am not sure it's the best possible solution but I just watched the auth0.isLoading and auth0.isAuthenticted:

```
watch(
  [() => auth0.isLoading, () => auth0.isAuthenticated],
  ([isLoading, isAuthenticated]) => {
    console.log("got here", isLoading.value, isAuthenticated.value);
    if (!isLoading.value && isAuthenticated.value) {
      // perform getAccessTokenSilently here
    }
  },
  { immediate: true, deep: true },
);
```

Now, it waits for it to stop load and authenticate me before requesting an access token.

Seems legit for this issue.

@ewanharris I still wonder, the way I get access token, save it to localstorage and attach it to my next api call, is this a legit way to do it? You suggest something else?

**Comment by ewanharris** [comment] 2023-08-09 12:13
@avivday2, waiting for at least `isLoading` to be true before retrieving the token should be good as that will ensure that the SDK has fully loaded before attempting any interactions. `isAuthenticated` should not be necessary, but it should avoid any `login_required` errors being returned from `getAccessTokenSilently`.

The sample repository contains a [Calling an API Sample](https://github.com/auth0-samples/auth0-vue-samples/blob/master/02-Calling-an-API/src/views/ExternalApi.vue) that retrieves an access token and calls an API if that is useful.

**Comment by frederikprijck** [comment] 2023-08-14 08:06
Closing, as it looks like it's answered. Can always reopen if needed, just let us know!

**Closed by frederikprijck** 2023-08-14 08:06 UTC
Labels: bug
