### ISSUE TITLE
[Vue 3 & Vite 2] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading ‘getTokenSilently’) 

### ISSUE THREAD

**Issue by onurusluca** [auth0/auth0-vue#108] opened 2022-04-18 06:51 UTC
Moving [this ](https://github.com/auth0/auth0-spa-js/issues/894) issue here cause I am still getting some errors. 

[Reproduction](https://github.com/onurusluca/auth0-vue-samples/tree/vite)
[Related code piece](https://github.com/onurusluca/auth0-vue-samples/blob/vite/02-Calling-an-API/src/views/Home.vue)
May be related: https://github.com/auth0/auth0-vue/issues/99

**When trying to use Auth0 outside of a .vue file, calling `getTokenSilently` will give error.**

Let's say we have a .ts file with some function with auth0 properties so that we can call them from a ,vue file to get for example accessToken:

```
import { useAuth0 } from "@auth0/auth0-vue";

async function getAppToken() {
  const { getAccessTokenSilently } = useAuth0();

  // do something
  const token = await getAccessTokenSilently();
  // do something else
  return token;
}

export { getAppToken };
```

And then we use it in a .vue file:

```
<template>
  <div>
    <button class="btn-success" @click="callApi">Call API</button>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import * as authHelper from "../authHelper";

onMounted(async () => {
  // Won't give Uncaught (in promise) TypeError. Only gives a normal 403 server error(unrelated, ignore) 
  const accessToken = await authHelper.getAppToken();
// do something

});

async function callApi() {
  // Gives: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading ‘getTokenSilently’) error reproduction
  const accessToken = await authHelper.getAppToken();
// do something
}
</script>
```

Calling the getAppToken in an onMounted won't give the` TypeError: Cannot destructure property 'getAccessTokenSilently' of 'useAuth0(...)' as it is undefined.` error but calling it from a function will result in error.

This may not be related to auth0 per se. May just be because of Vue3 Composition API Script Setup. Forgive me if so.

**Comment by frederikprijck** [comment] 2022-04-19 07:54
Duplicate of https://github.com/auth0/auth0-vue/issues/99

**Closed by frederikprijck** 2022-04-19 07:54 UTC
Labels: bug report
