### ISSUE TITLE
ESM Support. Wrong package exports. no .mjs file extension used.

### ISSUE THREAD

**Issue by awacode21** [auth0/auth0-vue#159] opened 2022-10-21 11:14 UTC
### Describe the problem

Within esm projects we cannot import '@auth0/auth0-vue' cause its commonjs.
i had a look on whats delivered by that package:
<img width="359" alt="Bildschirmfoto 2022-10-21 um 13 04 17" src="https://user-images.githubusercontent.com/30939926/197182168-2804edf1-0d08-4e25-80ad-e78553c66be2.png">
<img width="307" alt="Bildschirmfoto 2022-10-21 um 13 04 08" src="https://user-images.githubusercontent.com/30939926/197182179-e4489f60-900b-4e57-8611-4f8569a03496.png">
there are main and module configurations with wrong file endings. instead i guess you need in package.json export definitions for require and import based on .js and .mjs endings.

That results in errors:
<img width="1279" alt="Bildschirmfoto 2022-10-21 um 13 02 56" src="https://user-images.githubusercontent.com/30939926/197189900-598e01ba-fb43-4dca-9844-33839947e2c9.png">

Currently it seems the package is not esm ready. So i would like to ask to fix this as we really need it in our project urgently.

### What was the expected behavior?

esm package import to work as expected

### Environment

- **Version of `auth0-vue` used: *^1.0.2*
- **Version of `vue` used: *^3.2.37*
- **Which browsers have you tested in? *Chrome, but it is browser independant*
- **Other modules/plugins/libraries that might be involved: *"vite": "^3.1.8"*

**Comment by awacode21** [comment] 2022-10-21 11:34
and when trying to import this instead `'@auth0/auth0-vue/dist/auth0-vue.production.esm.js'` it is not working, i get erros like:
<img width="913" alt="Bildschirmfoto 2022-10-21 um 13 33 43" src="https://user-images.githubusercontent.com/30939926/197186723-d0af81ae-4d7a-4858-8b23-b47d8937ff81.png">

this is really a massive blocker on our project

**Comment by frederikprijck** [comment] 2022-10-21 11:51
Thanks for reaching out. I am a bit confused by the first screenshot of the error you shared. 
It's not mentioning our SDK, it's mentioning Swiper?

Are you sure the original error is caused by our SDK? If so, can you show the error you have before changing the import to `@auth0/auth0-vue/dist/auth0-vue.production.esm.js`, as per your second screenshot.

**Comment by awacode21** [comment] 2022-10-21 11:54
oh sorry, this was the wrong screenshot. i updated it to the right one.

**Comment by frederikprijck** [comment] 2022-10-21 11:58
Thanks, have you tried doing what it asks you to do?

```ts
import pkg from "@auth0/auth0-vue";
const {AUTH0_INJECTION_KEY} = pkg;
```
Does that work ?

**Comment by awacode21** [comment] 2022-10-21 12:01
Yes, when i do it that way it complains with the following error es you are not providing a default export 
<img width="1033" alt="Bildschirmfoto 2022-10-21 um 14 00 54" src="https://user-images.githubusercontent.com/30939926/197191071-28901a63-8f7e-453d-abc3-cbb5b6769689.png">

**Comment by frederikprijck** [comment] 2022-10-21 12:02
Ok thanks, any chance you have a small Vue project to reproduce this so we can have a look?

**Comment by awacode21** [comment] 2022-10-21 12:05
i could create a reproduction on stackblitz, but as i am working on a client project i for sure should not share on stackblitz the domain, audience and client id. Are there somekind of dummy mek accounts which i can use for?

**Comment by frederikprijck** [comment] 2022-10-21 12:09
A stackblitz would be best, or a small github project that I can look at.

I just created a new Vue project using vite that has `type` set to `module`, and I can import our SDK fine:
![image](https://user-images.githubusercontent.com/2146903/197192400-05f9ef2a-989b-4a66-b2a5-6e6556f806e7.png)

> Are there somekind of dummy mek accounts which i can use for?

You can create your own application on auth0.com for testing, or just leave those values blank in the stackblitz/project.

**Comment by awacode21** [comment] 2022-10-21 12:11
Were you also able to build and preview this? Because for me it was complaining in the browser

**Comment by frederikprijck** [comment] 2022-10-21 12:13
Yes, the console even outputs the correct symbol for the AUTH0_INJECTION_KEY: 

![image](https://user-images.githubusercontent.com/2146903/197193158-02a2ff8d-3f05-4ba3-b76a-8418a4fedf7f.png)

**Comment by awacode21** [comment] 2022-10-21 12:15
I'll prepare a reproduction on stackblitz

**Comment by awacode21** [comment] 2022-10-21 12:22
@frederikprijck quick question.. i created a free account. Where do i get the information for 'audience' from?

**Comment by awacode21** [comment] 2022-10-21 13:02
https://stackblitz.com/edit/vitejs-vite-rks7ks

my reproduction. Here i don't get the import error, which is strange i would expect it to be there. But here i always get 401 unauthorized from mek, which i also don't understand.. but why it is different than on my project... hm my project also uses SSR. I'll adjust the reproduction to be using SSR with vite. Let's see

**Comment by awacode21** [comment] 2022-10-21 13:37
@frederikprijck i have a running reproduction here: https://stackblitz.com/edit/vitejs-vite-lncyzq?file=package.json&terminal=build

Vite 3 with SSR / Vue / Auth0

**Comment by frederikprijck** [comment] 2022-10-24 07:43
Just a quick update:

I tried your reproduction locally, and was able to make it work when making the following changes to the `package.json` from our SDK:

```diff
-"main": "dist/lib/auth0-vue.cjs.js",
+"main": "dist/auth0-vue.production.esm.js",
"types": "dist/typings/index.d.ts",
"module": "dist/auth0-vue.production.esm.js",
+"type": "module",
```

What this means is that when using Vite SSR, it relies on the `main` value from the package.json, as well as the `type` value.  As our type is set to commonjs, vite will say it's a commonjs package. Even when setting `type` to `module`, vite will complain because it tries to use the `main` bundle, which is common js.

As we can't set our main to ESM, I am not sure there is much we can do from our side. But open to any improvement we can do without breaking existing users.

Having said that, [here is a fork of your StackBlitz that works](https://stackblitz.com/edit/vitejs-vite-azx6rw), all you need to do is add the followin to your vite config:

```ts
ssr: {
    noExternal: ['@auth0/auth0-vue']
}
```
This should remove the error. Would that work for you?

**Comment by awacode21** [comment] 2022-10-24 10:23
i think that he always loads commonjs is related to the used file endings... 
*.js fallbacks to commonjs... whereas with *.mjs it knows that it is esm... but as both of your files are using *.js he always thinks this is common.js.

i also know/recognized on other packages that when there are different export types, that they removed main/module from packages json and replaced by export definition. something like:

"exports": {
      "require": "index.js",
      "import": "index.mjs"
},

maybe that helps?

**Comment by awacode21** [comment] 2022-10-24 10:43
```
ssr: {
    noExternal: ['@auth0/auth0-vue']
}
```

worksaround it for now for me. But i think your cjs/mjs implementation is still not right and needs to be worked on.

**Comment by frederikprijck** [comment] 2022-10-24 10:54
As the workaround works, and this is the first time this issue has been raised, we're going to leave things as they are.

If you do believe we need to make changes to our setup to support ESM in a better way without breaking current users, we are always open to that. Feel free to open a PR and I am happy to look into it.

Closing this for now.

**Closed by frederikprijck** 2022-10-24 10:54 UTC
Labels: question

**Comment by awacode21** [comment] 2022-10-25 17:15
Seems like its not fully working... so it worked for the import.. but then when using the library.. when building and running for production i get other errors related to it:

<img width="1284" alt="Bildschirmfoto 2022-10-25 um 19 13 25" src="https://user-images.githubusercontent.com/30939926/197839576-5ae04927-0d53-4456-9482-532fea690299.png">

**Comment by frederikprijck** [comment] 2022-10-26 16:55
I dont think I understand what I am looking at, where is this coming from?

Probably makes sense to ensure the reproduction sample has the same error so we can look into it.
