### ISSUE TITLE
appState.target has undocumented dependency on using Vue Router

### ISSUE THREAD

**Issue by jrubinator** [auth0/auth0-vue#241] opened 2023-07-11 13:19 UTC
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using a Vue app without a Vue router, `appState.target` is ignored post-redirect (instead of being followed, per https://github.com/auth0/auth0-vue/blob/main/FAQ.md#3-user-is-redirected-to--after-successful-sign-in-with-redirect).

Instead, you will always be redirected to `/`

### Reproduction

1.  Update https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/components/NavBar.vue#L108 to something like
```
      login() {
        auth0.loginWithRedirect(
          {
            appState : { target: 'post-redirect' }
          }
        );
      },
```
2. Comment out use of Vue Router in https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/main.ts
```
app
  .use(hljsVuePlugin)
  //.use(createRouter(app))
  .use(
    createAuth0({
```
3. Configure your auth0 info and start up the app
4. Log in

At this point, you will be logged in to http://localhost:3000/, rather than http://localhost:3000/post-redirect

### Additional context

I think the source of the issue is https://github.com/auth0/auth0-vue/blob/main/src/plugin.ts#L165-L180, where we update the window history to be `/` but do not push a new route.

### auth0-vue version

2.2.0

### Vue version

3.3.4

### Which browsers have you tested in?

Chrome

**Comment by jrubinator** [comment] 2023-07-14 21:32
Sure! I have a CDN that is serving a couple different applications. They're mounted at different endpoints, like my.cdn.com/app-1 and my.cdn.com/app-2

One of these applications is actually a small demo site (let's say my.cdn.com/app-1), to support another application that expects to be embedded in an iframe. The embedded app in turn expects to be passed an auth JWT.

So the demo site allows users to log in at my.cdn.com/app-1 and then after login, redirects back to my.cdn.com/app-1, where it can then set up its embedded iframe. However, because of the rewrite, I end up at the root my.cdn.com, which eg. won't work upon refresh.

FWIW, I was able to work around this fairly easily by adding a dummy router, so this isn't stopping me from using auth0, and it's not causing too much pain now that I recognize the cause.

**Comment by frederikprijck** [comment] 2023-07-20 13:57
Thanks for that feedback. I am going to leave this issue open so I can get back to this and see if we can solve this, or add something to the readme.

**Comment by itzstatic** [comment] 2023-08-03 18:28
Just leaving this comment here as a related issue I experienced:

I am using Vue Router but was still having trouble getting my SPA to redirect to the intended protected page after handling the redirect callback.

It turns out I had to install router on our Vue instance **before** installing this plugin. Doing it in the opposite order will leave the app redirecting to /!

It would be nice if the logic in `__checkSession` could somehow be moved out of the plugin install and into say a deferred `nextTick` type of handler on app startup, seems like it would avoid dependency registration order problems, and also let that code throw exceptions.

**Comment by frederikprijck** [comment] 2023-08-03 18:51
@itzstatic this is by design and explicitly called out in our examples, see : https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md#protecting-a-route

**Comment by frederikprijck** [comment] 2023-08-22 12:32
I'm going to close this issue and leave things as is. If anyone comes up with the same issue as mentioned by the OP, please let us know and we can reconsider.

However, given users can mock the router and work around it (and the people using our SDK without a router seems to be rare), we won't action this at the current time.

Regardless, thanks for taking the time to report this!

**Closed by frederikprijck** 2023-08-22 12:32 UTC
Labels: bug
