### ISSUE TITLE
Endless redirection when "Blocked thrid party cookie" is enabled

### ISSUE THREAD

**Issue by AloisH** [auth0/auth0-vue#233] opened 2023-06-15 09:38 UTC
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When we enable the option to "block third-party cookies" on Chrome or Edge and if we force the user to log in when he enters the website, it will endlessly redirect the user.

What should happen: 
It should only redirect once for login.

### Reproduction

1. Enable "block third-party cookies" on Chrome
2. Clone auth0-vue-sample
3. Modify App.vue to force login when the user enters the website
```js
  async created() {
    await this.$auth0.checkSession();
    if (!this.$auth0.isAuthenticated.value) {
        await this.$auth0.loginWithRedirect();
    }
  },
```
4. Start the application
5. You will be endlessly redirected.

### Additional context

So far, the only way I found to fix it is to wait 500ms after calling 
```js
    await this.$auth0.checkSession();
```

Example of working version with the sample app
```js
import NavBar from "./components/NavBar.vue";
import Error from "./components/Error.vue";

const delay = (ms: number) => new Promise((res) => setTimeout(res, ms));

export default {
  components: {
    NavBar,
    Error,
  },
  async created() {
    await this.$auth0.checkSession();
    if (!this.$auth0.isAuthenticated.value) {
      // When "Block thrid-party cookies" is enabled the application will endlessly redirect the user.
      // If we wait 500 ms, it will work.
      await delay(500);
      if (!this.$auth0.isAuthenticated.value) {
        await this.$auth0.loginWithRedirect();
      }
    }
  },
};
```

### auth0-vue version

^2.2.0

### Vue version

^3.3.4

### Which browsers have you tested in?

Chrome, Edge

**Comment by frederikprijck** [comment] 2023-06-15 09:42
Hey,

When third party cookies are blocked you will need to use custom domains or refresh tokens. But even when using refresh tokens, it's still recommended to use custom domains.

See: https://github.com/auth0/auth0-vue/blob/main/FAQ.md#1-user-is-not-logged-in-after-page-refresh

The infinite redirect is caused by your own code. Can you try and ensure you only call checkSession when isLoading is false?

Thanks

**Comment by AloisH** [comment] 2023-06-15 09:50
Hey !
Thank you for the quick reply.

I just tried waiting that isLoading = false, 
but the issue remains.

Here is the code is used 
```js 
async created() {
    await (this.$auth0 as any).__refreshState();
    console.log(this.$auth0.isLoading.value); // false
    await this.$auth0.checkSession();
    if (!this.$auth0.isAuthenticated.value) {
      await this.$auth0.loginWithRedirect();
    }
  },
```

**Comment by frederikprijck** [comment] 2023-06-15 09:53
What I think is happening is that checkSession will fail due to third party cookies (solved by custom domains or refresh tokens).

Can you verify the following:

```
async created() {
    await (this.$auth0 as any).__refreshState();
    console.log(this.$auth0.isLoading.value); // false
    console.log(this.$auth0.isAuthenticated.value); // IS THIS TRUE?
    await this.$auth0.checkSession();
    console.log(this.$auth0.isAuthenticated.value); // IS THIS FALSE NOW?
    if (!this.$auth0.isAuthenticated.value) {
      await this.$auth0.loginWithRedirect();
    }
  },
```

I assume `isAuthenticated` is true before calling checkSession, and false after. That's confusing but expected when third party cookies are blocked without custom domains or refresh tokens.

**Comment by AloisH** [comment] 2023-06-15 09:57
I just tried your code but `isAuthenticated` is always false

I found a way to fix it without having to call `refreshState()`
```js
watch: {
    "$auth0.isLoading.value": async function () {
      await this.$auth0.checkSession();
      if (!this.$auth0.isAuthenticated.value) {
        await this.$auth0.loginWithRedirect();
      }
    },
  },```

I will make a repo that reproduce the bug !

**Comment by frederikprijck** [comment] 2023-06-15 09:58
Not sure I understand what bug you want to report if you say the above code fixes it. As that's exactly what I asked, to wait for isLoading to be false.

I don't think the above code shows a bug, but is exactly what you want.

**Comment by frederikprijck** [comment] 2023-06-15 10:03
Something like `<sub-root-that-holds-everything-for-auth0 v-if="!$auth0.isLoading"></sub-root-that-holds-everything-for-auth0>` should work.

So yeah, I do use the SDK outside of that sub-root, but only for isLoading.

Technically, it's also okay to use isAuthenticated and user outside of that sub-root component, as long as you rely on Vue's reactivity as the values only reflect the accurate state when isLoading is false.

Closing as I think it's answered. Happy to continue the conversation as needed.

**Closed by frederikprijck** 2023-06-15 10:03 UTC
Labels: bug
