### ISSUE TITLE
Redirect to appState.target does not work

### ISSUE THREAD

**Issue by danstooamerican** [auth0/auth0-vue#255] opened 2023-09-04 17:23 UTC
### Checklist

- [ ] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am migrating to the new auth0-vue library. So far it has been a smooth ride but I am struggling with the last step. I want to return my users to the page they were initially routed to after they are successfully authenticated. There are two ways a user is asked to authenticate. Either by visiting a protected route or through a button on a login page. 

The login page uses the `loginWIthRedirect` function: 

```
auth0.loginWithRedirect({
  authorizationParams: {
    connection: <tenantId>,
    redirect_uri: window.location.origin + '/pub/callback',
  },
  appState: {
    target: '/default-route',
  },
})
```

Protected routes use a route guard:

```
createAuthGuard({
    app,
    redirectLoginOptions: {
      authorizationParams: {
        connection: <tenantId>,
        redirect_uri: window.location.origin + '/pub/callback',
      },
    },
  })
```

The callback route is not protected and only displays a loading page without any logic. From what I read in the documentation and examples I would expect my callback route to be called. Afterwards, the state is extracted and the user is routed to the intended page.

The router is configured with the following routes:

```
const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: availableRoutes.app_base,
    component: () => import('layouts/MainLayout.vue'),
    redirect: { name: defaultRoute },
    children: [
      {
        path: '',
        name: defaultRoute,
        props: true,
        component: () => import('pages/PersonalDashboardPage.vue'),
      },
	  ...
    ],
  },
  {
    path: '/pub/',
    component: () => import('layouts/PublicLayout.vue'),
    children: [
      {
        path: 'login',
        name: availableRoutes.login,
        props: true,
        component: () => import('pages/public/LoginPage.vue'),
      },
    ],
  },
  {
    path: '/pub/',
    component: () => import('layouts/FakeMainLayout.vue'),
    children: [
      {
        path: 'callback',
        name: availableRoutes.callback,
        props: true,
        component: () => import('pages/public/LoginCallbackPage.vue'),
      },
    ],
  },
  {
    path: '/:catchAll(.*)*',
    redirect: { name: defaultRoute },
  },
];
```

### Reproduction

Step 1: Configure the library as stated above
Step 2: Visit the protected route or click the login button
Step 3: Provide credentials
Step 4: The callback page is displayed
Step 5: No redirect to the intended page

I can observe that the URL is changed to `window.location.origin` without the `code` and `state` parameters. However, the site is not refreshed.

### Additional context

I am using the Quasar framework (v2.12.5).

I ensured that the router was initialized before auth0. The route guard is created with the correct Vue instance.

### auth0-vue version

2.3.1

### Vue version

3.3.4

### Which browsers have you tested in?

Chrome, Edge, Firefox

**Comment by frederikprijck** [comment] 2023-09-05 06:20
Thanks for reaching out.

How did u configure the guard ?

**Comment by frederikprijck** [comment] 2023-09-05 07:18
Thanks for reaching out and providing the above information .

I will have a look and see if this is something that can be reproduced based on what's provided.

I do want to mention we have no explicit support for Quasar, and I am wondering if the issue could be related to Quasar.

**Comment by frederikprijck** [comment] 2023-09-05 09:59
I managed to reproduce this, and have a fix ready. I do need to do some more testing.

Can you verify it works when you try the following:

- git clone git@github.com:auth0/auth0-vue.git
- cd auth0-vue
- git checkout fix/configurable-router
- npm pack

This will create a file called `auth0-auth0-vue-2.3.0.tgz`, you will need this later.

Then in your quasar project, update your bootfile to pass the router to our SDK:

```
export default boot(async ({ app, router }) => {
  // something to do

  app.use(
    createAuth0(
      {
        domain: '...',
        clientId: '...',
        authorizationParams: {
          redirect_uri: window.location.origin,
        },
      },
      {
        router, // <= add this
      }
    )
  );
});
```

Then in your quasar project, also do:

- npm uninstall @auth0/auth0-vue
- npm install ../path/to/auth0-auth0-vue-2.3.0.tgz

When you then run the project, does it work as expected?

**Comment by danstooamerican** [comment] 2023-09-05 13:17
Thank you for your effort and fast response! Your patch works for the route guard. However, when I call the `loginWithRedirect` function directly it seems to redirect me to the base path `/`.

```
auth0.loginWithRedirect({
  authorizationParams: {
    connection: <tenantId>,
    redirect_uri: window.location.origin + '/pub/callback',
  },
  appState: {
    target: '/default-route',
  },
})
```

**Comment by danstooamerican** [comment] 2023-09-05 13:20
I saw that you look for the router at `app.config.globalProperties.$router`. Wouldn't it be a better fix to expose the router through this variable in a boot file?

**Comment by danstooamerican** [comment] 2023-09-05 13:51
I changed my boot file to this. I register my route guard which is a simple wrapper around the `createAuthGuard` provided by the library. The important part is the last line `aApp.config.globalProperties.$router = aRouter` which exposes the router so the library can find it.

```
export default boot(({ app, router }) => {
  const aApp = app as App;
  const aRouter = router as Router;

  const baseRoute = aRouter
    .getRoutes()
    .find((route) => route.name === availableRoutes.app_base);

  if (baseRoute) {
    baseRoute.beforeEnter = authenticationRouteGuard(app);
  }

  aApp.config.globalProperties.$router = aRouter;
});
```

With these changes, everything works as expected :)

**Comment by frederikprijck** [comment] 2023-09-05 15:19
Not sure how that would be different from what I mentioned [here](https://github.com/auth0/auth0-vue/issues/255#issuecomment-1706314567).

I assume we can close this tho, as it looks like you managed to work around it. If not, let me know and I can reopen.

**Closed by frederikprijck** 2023-09-05 15:19 UTC
Labels: bug

**Comment by danstooamerican** [comment] 2023-09-05 18:14
> Not sure how that would be different from what I mentioned [here](https://github.com/auth0/auth0-vue/issues/255#issuecomment-1706314567), but the benefit is that your solution doesnt need any changes to the SDK so that's arguably better for sure.
> 
> I assume we can close this tho, as it looks like you managed to work around it. If not, let me know and I can reopen.

Since you don't explicitly support Quasar and it seems to be a Quasar issue, I like my solution better. I would treat this variable as an API I have to follow. If my environment doesn't do it out of the box, then I have to work around it and not the other way around. Your solution also didn't fully work. Perhaps the router is not propagated correctly?
