### ISSUE TITLE
Be able to access Auth0Client outside a component

### ISSUE THREAD

**Issue by frankkoornstra** [auth0/auth0-vue#99] opened 2022-03-19 15:31 UTC
### Describe the problem you'd like to have solved

This plugin makes life a lot easier in Vue3 so thank you for that but there's one thing I can't seem to figure out: how to access the Auth0Client outside a component.

I'd like to use the Auth0 client to add a `Authorziation: Bearer` header to my Apollo requests with the help of [`setContext`](https://www.apollographql.com/docs/react/api/link/apollo-link-context/#overview). I tried using `useAuth0()` but this doesn't work because Vue cannot use `inject` outside the scope of a component.

### Describe the ideal solution

Be able to access the Auth0Client instance in _and_ outside components.

### Alternatives and current work-arounds

The [given example](https://github.com/auth0/auth0-vue#calling-an-api) requires me to provide the authorization header every time I make a request; that's quite a bit of duplication.

**Comment by BrentonCozby** [comment] 2022-03-22 02:49
Could it be as simple as exposing `client` from `/src/plugins.ts`?

https://github.com/auth0/auth0-vue/blob/main/src/plugin.ts#L15

**Comment by frederikprijck** [comment] 2022-03-22 08:11
Thanks for reporting, I understand the limitation here and will have a look into what we can do with today's SDK and if and how we can improve the experience here.

I believe passing around the client is something you want to avoid if not necessary. Happy to export the client if that is the only way to achieve what needs to be achieved here. However, I would be interested to figure out why you are getting that error first @BrentonCozby, as I believe it's better to focus on what we want to achieve rather than a specific solution, even if the outcome will eventually be exposing the client.

**Comment by BrentonCozby** [comment] 2022-03-22 09:41
> I would be interested to figure out why you are getting that error first @BrentonCozby, as I believe it's better to focus on what we want to achieve rather than a specific solution, even if the outcome will eventually be exposing the client.
> 
> 

Agreed--even if the client was exposed, I can't yet confirm that vite wouldn't give me the same error. I'll investigate further. Thanks for acknowledging @frederikprijck .

**Comment by BrentonCozby** [comment] 2022-03-22 09:47
@frederikprijck Also, I was hoping you might be able to explain why the client isn't exposed? I assume it's for security, but I'm not sure how and I'd like to know what the risks are, for learning sake.

**Comment by frederikprijck** [comment] 2022-03-22 09:54
@BrentonCozby There is no real reason why it isn't exposed. Definetly not for security reasons, as you would typically use that Client directly when u use Auth0-SPA-JS.

With our initial beta and GA release, we didn't expose the client because we prefer people to use our Vue tailored API (using Options or Composition API), so we saw no need to expose it.

That said, things like this issue are good candidates for revisiting that. But I think we should be mindful and see if it actually needs to be exposed or if there are other ways to solve this.

**Comment by BrentonCozby** [comment] 2022-03-23 14:57
Thanks for sharing--that does show me a pattern I hadn't considered before. However, I'd still like to be able to keep _some_ code separate from Vue.

Currently, I'm just passing the token up the chain from Vue --> [vue-query](https://vue-query.vercel.app/) (grabs token from auth0 here) --> axios:

https://github.com/BrentonCozby/photos-app/blob/main/spa/src/composables/photos/useGetPhotos.ts#L25

^ `useGetPhotos` is used in App.vue and `PhotosApi` uses axios

**Comment by frederikprijck** [comment] 2022-03-23 15:48
Hey @BrentonCozby ,

Wouldnt this work with something like this? 
https://github.com/auth0-samples/auth0-vue-samples/commit/5933fe850bd19a1278af1c10fdcdf151fd27288d

I believe the patterns used in both commits go beyond our SDK and show how you can go outside of a component, while still being inside of a component.
I am pretty sure you can create several alternatives on this pattern that might fit your use-case more.

Again, not saying we don't want to expose the client, just not sure it's needed here.

**Comment by BrentonCozby** [comment] 2022-03-30 00:07
@frederikprijck that's a nice trick with `useAxios`, but it still requires that I add `useAxios()` (instead of `useAuth0()`) to every component. I'd rather import only `usePhotoService()`, for example.

**Comment by frederikprijck** [comment] 2022-03-30 07:52
I am still not sure I follow with what the problem is here. I update the example application that now only requires you to use `useExternal` in your components, see: https://github.com/auth0-samples/auth0-vue-samples/commit/57fbbb5cadfe1ada49d2935d0f8d7c43010b0d53. 

Keep in mind that in this case, you can still only call `useExternal` from inside a component. But from the looks of it, this still achieves what you are trying to achieve. I think it's important that once you start using `usePhotoService` and the like, you shouldn't leave the component context. It's a slightly different way to achieve things, and does complicate things when you start mixing approaches. The same complication exists in React when u use React Hooks and try to use things outside of the Context.

Using auth0-spa-js can definetly be useful for more complicated projects, our SDK is intended to solve most issues for our Vue users in such a way that they can use Auth0 in Vue with minimal code, but those that have specific needs can always rely on Auth0-SPA-JS directly.

However, having said that, I do believe that we want to keep as much users with our Auth0-Vue SDK, so we are definetly open to ensure both yourself and the OP can achieve what they want with the SDK. If that would mean exposing things, we could. But what I want to avoid is expose so much that in the end you are almost using it as if you are using Auth0-SPA-JS.

**Comment by purepear** [comment] 2022-03-30 17:04
From what i understand by reading the source code, the auth client is "encapsulated" in an app instance in order to support multi-app projects. This makes it hard to access it outside of an app context.

**Comment by onurusluca** [comment] 2022-04-06 06:30
Just to say I also have the same problem using the Auth0 outside of component: https://github.com/auth0/auth0-spa-js/issues/894

I am thinking of using auth0-spa-js too but I also had some problem with that too using with Vite Vue 3 Composition API script setup. See the above link. And later in the comments, Auth0 Vue-SDK is mentioned thanks to @frederikprijck

**Comment by BrentonCozby** [comment] 2022-04-06 12:04
@frederikprijck might you be able to answer this question from my last comment?

> maybe it's possible I could use some utils from auth0-vue, such as `createAuth0ClientProxy`?

**Comment by frederikprijck** [comment] 2022-04-08 07:14
Apologies for the radio silence here, we will be discussing this subject internally on how we should move forward here, and will get back to you as soon as possible.

**Comment by Soviut** [comment] 2022-04-10 19:01
What I wound up having to do was create my own "model" plugin that creates the Apollo client, sets up some auth middleware and directly fetches the Auth0 client from the `app.globalProperties`. I couldn't even use the `AUTH0_TOKEN` since it's not exported, so I had to use the raw `$auth0` string

**model.ts** (plugin)
```typescript
export const clientKey = Symbol('modelClient')

export function createModel(): Plugin {
  return {
    install: (app) => {
      const authMiddleware = setContext(async () => {
        // HACK: get client key directly from app
        const auth0 = app.config.globalProperties['$auth0'] as Auth0VueClient
        const accessToken = await auth0.getAccessTokenSilently()

        return {
          headers: { authorization: `Bearer ${accessToken}` },
        }
      })

      const httpLink = new HttpLink({
        uri: import.meta.env.VITE_API_URL,
      })

      const client = new ApolloClient({
        cache: new InMemoryCache(),
        link: from([authMiddleware, arternalHttpLink]),
      })

      app.provide(clientKey, client)
    },
  }
}

export function useModelClient() {
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  return inject<ApolloClient<NormalizedCacheObject>>(clientKey)!
}
```

I refactored my models to use dependency injection so the client didn't need to be imported directly into the module.

```typescript
// note the function inside a higher order function to do dependency injection
const useGet = (client: ApolloClient<NormalizedCacheObject>) =>
  async (id: string): Promise<InvoiceTemplate> => {
    const { data } = await client.query({
      query: gql`...`,
    })
    return data.transaction_template_by_pk
  }

// group all the injection under one function to make accessing the actions simpler
export const useTemplateModel = (client: ApolloClient<NormalizedCacheObject>) => {
  return {
    get: useGet(client),
  }
}
```

I can then consume this anywhere in my Vue app as a composable.

```html
<script setup lang="ts">
import { useModelClient } from '@/plugins/model'
import { useTemplateModel } from '@/models'

const modelClient = useModelClient()
const templateModel = useTemplateModel(modelClient)

const template = await templateModel.get('12345')
</script>
```

**Comment by frederikprijck** [comment] 2022-04-11 07:30
@Soviut Thanks for sharing that. I believe that definetly is something I would prefer myself. 
I will ensure AUTH0_TOKEN is exported.

That said, that doesn't help to access things outside of the vue component. However, I think ideally you want to not do those things outside of a Vue component.

If you do, I am also pretty sure you can write your own plugin that does something like this:

```

export const client: Ref<Auth0VueClient> = ref(null);

export function exposeAuth0() {
  return {
    install(app) {
      client.value = app.coonfig.glboalProperties['$auth0']
    }
  }
}
```

Basically this plugin takes our client, and exposes it more globally. Wouldnt recommend, but I would say it should be doable without making any changes in our SDK that opens doors for people to start misusing that flexibility.

**Comment by Cmacu** [comment] 2022-04-14 06:46
I stumbled upon this too.
In our case, we are trying to integrate auth0 into a quasar application.
I am not sure I understand why this plugin uses the provide/inject api, which creates the limitation that it can only be used within Vue components. 
There are plenty of use cases (store management, APIs, web components, etc) where we should be able to import the client and use authentication details (status, token, user information, etc) outside without the constraints of making sure the code is executed from within a setup function.
I guess that part of the problem is that the plugin maintains a state and a having a single instance might be important, but there are other patterns outside of the provide/inject api where this should be achievable.

**Comment by frederikprijck** [comment] 2022-04-14 08:00
Thanks for chiming in. As mentioned, we value feedback and definitely want to ensure you can continue using our SDK.

Are the mentioned solutions not working for you? If not, can you elaborate why not and how we can improve?

> I am not sure I understand why this plugin uses the provide/inject api, which creates the limitation that it can only be used within Vue components.

What are you suggesting as an alternative?

> In my understanding big part of the concept/design for the composition api is to be able to use any bits and peaces as needed without the constraints and context of a component.

Not sure I understand that, but I am more than happy to try and understand what you mean and how we can do better.

**Comment by Soviut** [comment] 2022-04-14 15:29
> In my understanding big part of the concept/design for the composition api is to be able to use any bits and peaces as needed without the constraints and context of a component.

This is true up to a point; you can use parts of the Vue 3 API (like ref, reactive, etc.) outside of Vue components. However, if you want to take advantage of the provide/inject pattern that plugins rely on, then at some point you need to wrap that functionality.

@frederikprijck I think that there are two complimentary changes that could be made. The first would be to expose the client that `auth0/auth0-vue` sets up. The second would be to allow an existing client created with `auth0-spa-js` to be passed to `createAuth0()`. In both cases it eliminates duplicate clients and satisfies most use cases of internal vs external setup.

**Comment by Cmacu** [comment] 2022-04-14 17:58
I am not able to speak for the rest of the developers, but here are my thoughts:

1. Purpose
Authentication itself and checking if user is authenticated/authorized  is not a display/component/framework problem. Displaying status/username/etc might be part of the interface, but that's only small and relatively minor part of the authentication role in an application. Enabling these details in a component is should be possible regardless of the provide/inject api.

2. Usability
There is no limitation of importing external modules within Vue components, the limitation is the other way around. This makes the usability of this plugin limited and complicated in wide variety of scenarios. Another part is that the way this is handled is not completely transparent and obvious for the developer. `useAuth0` returning undefined outside of component context or working in certain scenarios is really dangerous and hard to reason when working with third party APIs

3. Extendability
Being able to wrap the plugin within a module to extend/modify/improve functionality is critical. This is severely limited by the requirement that the wrapper has to be a component or depend on component. User authentication or logout has a lot of side/invisible effects such as setting up states, calling APIs, enabling features, re-routing, etc. The authentication itself is a pre-requisite for a lot of the functionality to happen. It's unnecessary and more complicated to add additional requirement like executing this logic within the context of a component.

4. Modularity
There are multiple use cases mentioned in this issue where external (often third party) modules depend on authentication. We can't always control how these modules relate to the app/component context and making this a requirement significantly increases the complexity and flexibility to integrate them together.

There is also the problem that I don't really understand the need to manage the plugin via the provide/inject api. I understand the guidelines aspect of it and the ability to make it possible, but don't understand the idea of making it a hard requirement. Every other third party library I've used with Vue 3 so far (including the ones mentioned in this issue) is possible to integrate both via provide/inject as well as an external module. I can't think of another plugin that has the component context hard requirement.

**Comment by Soviut** [comment] 2022-04-14 19:02
@Cmacu the need for provide/inject is so that client can be defined a config time (in `main.ts`) and that client can be shared throughout the app by calling `useAuth0`. Without the provide on the Vue `app`, there is nothing for `useAuth0` to inject.

**Comment by Cmacu** [comment] 2022-04-14 19:09
> @Cmacu the need for provide/inject is so that client can be defined a config time (in `main.ts`) and that client can be shared throughout the app by calling `useAuth0`. Without the provide on the Vue `app`, there is nothing for `useAuth0` to inject.

The client can be defined at config time in main.ts without depending on the provide/inject api and can also be passed to provide/inject. Correct me, if I am wrong, but the role of provide/inject is to insure a single state through all components of the app. This can be achieved in multiple other ways while still providing that same state/client via provide/inject to align with the guidelines.

**Comment by Soviut** [comment] 2022-04-14 19:14
@Cmacu You are correct in that it's generally used for maintaining a central state or instance that can be accessed anywhere in the component hierarchy. However, another big factor is that it allows for loosely coupled composables, rather than tightly coupled direct imports. It's far easier to test a component using composable than it is with direct imports.

**Comment by Cmacu** [comment] 2022-04-14 19:42
@Soviut as mentioned the provide/inject api which enables this loosely coupled compassable is still available. I am not sure I understand what makes it different. Let's say for example that there is a singleton client that is initiated in main.ts, made available externally, but also provided inside Vue context. How does that change the way a component injecting `useAuth0` would be tested?

**Comment by frederikprijck** [comment] 2022-04-14 20:41
> useAuth0 returning undefined outside of component context or working in certain scenarios is really dangerous and hard to reason when working with third-party APIs

@Cmacu, `useAuth0` is only expected to be used with the composition API, inside a component's setup function. Pretty much the same as libraries like [Vuex ](https://github.com/vuejs/vuex/blob/main/src/injectKey.js#L5-L7)or [Vue-Router](https://github.com/vuejs/router/blob/main/src/useApi.ts#L10-L12). I don't think the intention of the `useX` methods is to be used outside of a Vue component.

If you aren't trying to access things inside the setup function of your component, but still inside a component, you can rely on the fact that the SDK is also exposed on the `globalProperties`. In the case you need to use the SDK outside of a component, you can already do so with a few additions, as mentioned [above](https://github.com/auth0/auth0-vue/issues/99#issuecomment-1094650012).

**Comment by Cmacu** [comment] 2022-04-14 21:09
@frederikprijck but your examples for `useStore()` and `useRouter()` work just fine outside of component context... What makes you think they don't?

**Comment by frederikprijck** [comment] 2022-04-14 21:30
@Cmacu [here ](https://codesandbox.io/s/gallant-shirley-6e8f56)is a codesandbox showing how it logs `undefined` when trying to access it from outside a component. You can also see that it outputs a warning in the console

```
[Vue warn]: inject() can only be used inside setup() or functional components. 
```

If you would be able to update the codesandbox to demonstrate how you would make the import work, that would be super helpful thanks!

**Comment by Cmacu** [comment] 2022-04-14 21:43
That's interesting, we use it in multiple places inside `axios` interceptors (to redirect on expired token), in web socket module (to open a page on certain events) and for inhouse reactivity api based store (to update the url when filters are applied). None of these modules are inside Vue component setup context and it doesn't return `undefined`.

My guess is that this has something to do with the way your component is initialized (perhaps the code is executed prior to `Vue.createApp()`?

But even, if this is a limitation/constraint of the Vue provide/inject api. Wouldn't it be possible to import the auth0 client directly without the use of inject?

**Comment by Cmacu** [comment] 2022-04-14 21:49
In our case we will stick with the `auth0-spa-js` since it doesn't have the above limitations, although it has no TypeScript support and requires custom integration. I was hoping that this plugin would offer a better and more streamlined solution.

**Comment by frederikprijck** [comment] 2022-04-14 21:59
> although it has no TypeScript support

Auth0-SPA-JS is written in TypeScript and ships with all the required types, so there shouldn't be any issue integrating with TypeScript projects.

> I was hoping that this plugin would offer a better and more streamlined solution.

I believe the intention of this plugin is make integration in Vue easier, while probably not covering 100% of the use-cases. Anyone having a very specific or complicated use-case can always fall back on using Auth0-SPA-JS.
That said, we are always open to gather feedback and see if we can/should improve certain areas.

> Wouldn't it be possible to import the auth0 client directly without the use of inject? I think this will be common problem for developers trying to use this plugin.

That's the main reason this issue was opened, and it's still open because we believe there are workaround being mentioned, but are still considering whether we should make a change to our SDK to improve the experience.

However, keep in mind that, given [the mentioned workaround](https://github.com/auth0/auth0-vue/issues/99#issuecomment-1094650012), you should already be able to use this SDK outside of the context of a component.

**Comment by Cmacu** [comment] 2022-04-14 22:19
@frederikprijck my bad on the TypeScript support. I don't know how we missed that when we did the initial integration or if it wasn't available.

Regarding the mentioned workaround, where does the app argument come from?
One thing I should mention is that we using quasar. Quasar doesn't expose directly the `createApp` nor `main.js`. Plugins are installed via [boot files](https://quasar.dev/quasar-cli-webpack/boot-files). That could be another reason that the inject is available for us in external modules (but not in the case of this plugin)

**Comment by frederikprijck** [comment] 2022-04-14 23:04
I added a draft PR that makes a change to the SDK that I believe should allow the usage of this SDK outside of a component.

In essence, I [reworked the internal structure of the plugin](https://github.com/auth0/auth0-vue/commit/8f22698e33a8cc525878b92a9c9ea6914db2f8ea) to allow the creation of the plugin to be moved to an external file:

```ts
export const auth0 = createAuth0({ ... });
```
Next, you can import the exported plugin instance when configuring the Vue app.
```ts
import { auth0 } from './auth0';

createApp(App)
  .use(auth0)
  .mount('#app');
```
However, you can now also import the exported plugin instance anywhere else and access it's methods
```ts
import { auth0 } from './auth0'

export async function getAccessTokenSilentlyOutsideComponent(options) {
  return auth0.getAccessTokenSilently(options);
}
```
Even though this pattern was already possible before, previously we didn't expose the SDK's methods on the object returned by `createAuth0`. However, looking at popular plugins it appears to be common practice to keep the methods on the same instance that is used to pass to `app.use()`, allowing to use the SDK outside of a component using a structure mentioned above.

Here is a link showing how you can use the SDK with the changes: https://github.com/auth0/auth0-vue/commit/1590a84842d63a2c0003feb62fe6f9d8661285bd

Would this work for your situation @Soviut @BrentonCozby @frankkoornstra ?

**Comment by Cmacu** [comment] 2022-04-14 23:37
@frederikprijck this looks great! Really appreciate the discussion and you coming up with a solution so fast.

**Comment by BrentonCozby** [comment] 2022-04-15 01:35
@frederikprijck as I mentioned previously, I already decided to go with the spa sdk basically out of principle that the auth logic should be independent of Vue.

I appreciate you putting up a draft PR, but I'm not certain I would switch back to the Vue sdk based on what I said in the paragraph above. That being said, I have some questions/suggestions about your draft PR:

1. Why still use a plugin? Why not a composable instead?

2. I think you should rename the auth0 export to auth0Plugin so it's clear that you're passing a plugin to app.use() and so it's clear that a Vue plugin is being imported into a non-Vue context (which brings me back to my first question, above). However, I think an auth0 client instance (not the plugin instance) should be exported and that this client instance should have zero vue-specific code in it. The composable I mentioned in my first question would wrap the non-Vue client instance to make it reactive for Vue. I've mentioned this before, so I must assume it just got lost in all the other comments or that you have hesitations about this approach; if you have hesitations with this, what are they?

**Comment by Soviut** [comment] 2022-04-15 03:08
> 1. Why still use a plugin? Why not a composable instead?

Because the client still needs to be initialized at some point so it can be used in provide/inject in a composable. The client is async and essentially a singleton; you get weird behaviour if you try to use two clients at once (the issue I ran into when mixing the Vue plugin and auth0-spa-js.

> 2. I think you should rename the auth0 export to auth0Plugin so it's clear that you're passing a plugin to app.use() and so it's clear that a Vue plugin is being imported into a non-Vue context

The developer would write that export and can make the variable whatever they want. The pattern that @frederikprijck is using is the same that's Vue Router uses; you use `createRouter()` to export from a `router.ts` file, then import that router in your `main.ts` and `app.use(router)`. Vue i18n encourages similar patterns so you don't wind up with a giant `main.ts`.

> I hope it is clear that I would prefer to primarily use the spa sdk and that I'd love to also install a Vue composable that receives an existing auth0 client from the spa sdk. That is how I'm currently doing it in the example from my previous comment, except that I've created the Vue composable instead of installing it from npm.

This is why I recommended that `createAuth0()` be able to optionally take an auth0 client as its first arg. That way your existing auth0 client could be integrated and get all the reactive bonuses without reinitializing the client.

**Comment by frederikprijck** [comment] 2022-04-15 06:38
I agree with the replies from @Soviut , I believe a plugin is needed and the naming should not include Plugin, as we are not returning just a plugin, but the actual API to interact with, this is identical to a lot of popular plugins.

> The composable I mentioned in my first question would wrap the non-Vue client instance to make it reactive for Vue

I don't think composables exist to replace plugins in any way. As mentioned by @Soviut, a plugin is typical to register things in Vue-land. You can however do things differently, but I don't think creating an Auth0Client and consuming it with a composable is how we want to do this. I understand this is the solution you are pinned on, but not something I believe we should encourage to the majority of users.

> I'm open to installing only the Vue sdk instead of both the spa and Vue sdks, however, I'd like the non-Vue auth0 client to be exported from the Vue sdk.

I think that would make little sense. Our framework specific SDKs (Angular, React, Vue) are all thin wrappers to give you acces to the API in a way tailored for the framework in question, exposing the client would remove all reactivity we added and bypasses any of our Vue SDK, making it very realistic people will eventually end up with issues.

I believe with the proposed PR, you should be able to use our SDK outside of the context of a Vue component.
As mentioned before it looks like you want to use a dependency entirely unrelated to Vue, which you are fine to continue doing if that's what you prefer.

**Comment by frederikprijck** [comment] 2022-04-15 06:43
@Soviut 

> This is why I recommended that createAuth0() be able to optionally take an auth0 client as its first arg. That way your existing auth0 client could be integrated and get all the reactive bonuses without reinitializing the client.

I understand that it would be better for `createAuth0` to accept an Auth0Client than it would be for our Vue SDk to expose the native client. Regardless, I don't believe this is something we should do because this opens up doors to start shooting yourself in the foot.

As I have mentioned before, if you do have such a specific need, you are probably safer to use SPA-JS direcly, instead of mixing the two and hoping they will work correctly together. Imagine an application where half of it uses our client through the useAuth0 composable, and the other hals uses the native client directly. The latter would result in our reactive properties not reflecting what's changes, causing weird behavior and probably bugs.

**Comment by BrentonCozby** [comment] 2022-04-15 08:40
Ah, I see the need for the plugin. Thanks. That's fine. I still would prefer to use an instance of Auth0Client instead of a plugin instance in a non-Vue context, but I suppose it doesn't matter as long as it works.

**Comment by onurusluca** [comment] 2022-04-19 09:16
I am writing here as my issue was closed due to duplicate.

> As I have mentioned before, if you do have such a specific need, you are probably safer to use SPA-JS direcly,

I don't think this is any specific at all. This is very common. We need ways to customize auth.

I got everything working but now have these problems I've mentioned in my issue. I have to go back to spa-sdk too which is very unfortunate. Hope this will be changed. Without a way to use auth outside the component, we can't really use auth0 properly in my opinion.

**Comment by frederikprijck** [comment] 2022-04-19 09:57
@onurusluca please keep in mind that what you want to achieve already works today, see the workaround mentioned here: https://github.com/auth0/auth0-vue/issues/99#issuecomment-1094650012

**Comment by onurusluca** [comment] 2022-04-19 10:04
> @onurusluca please keep in mind that what you want to achieve already works today, see the workaround mentioned here: [#99 (comment)](https://github.com/auth0/auth0-vue/issues/99#issuecomment-1094650012).
> 
> But yes, we are planning to patch the SDK to make this work without the workaround.

I am sorry. Forgive my ignorance, I can't see how I can use that workaround to export getTokenSilently(or getAccessTokenSilently) and solve my problem. I am not very familiar with auth0. 

Could you elaborate please?

**Comment by frederikprijck** [comment] 2022-04-19 10:07
This is not related to Auth0, but to Vue. What you want is create a new plugin as I mentioned in my comment, the plugin sets the instance of our SDK to a global client variable.

Next, anywhere u need u can now inject the client and use `unref(client).getAccessTokenSilently()`.

**Comment by set321go** [comment] 2022-04-19 16:39
@frederikprijck i've been following along! 

Is this then the suggested way of accessing the auth0 client (without your PR)? 

I'm relatively new to vue but I think something thats missing from the documentation is some examples using vuex/pinia, with my limited knowledge I would take what has been talked about here (looking for how to integrate with a store is what got me here in the first place) and somehow shoehorn that into my store but that might be completely the wrong approach. 

it might be some minor changes to the login/logout/profile examples are all that are needed to do it 'properly' I think most people are just after that 'store the profile and login state' use case.

**Comment by onurusluca** [comment] 2022-04-20 02:30
> 

Thanks for the reply. Does this use aut0-vue or spa-js? Or do we have to use both?
Things got a little complicated.

Took a look at [here ](https://github.com/auth0/auth0-vue/tree/feat/rework-plugin/playground) but it is a little mixed up in my head.

I can't get everything work together.  It doesn't work with my code. I changed a lot but now nothing works. lol

Would you mind creating a new branch only for this purpose that is using auth0 outside the component. 
I think this will be very difficult for newcomers as well.

Let me share my simplified code using aut0-vue

**main.ts**
```
import { createAuth0 } from "@auth0/auth0-vue";
import { EnvConfig } from "@/backend/env-config";

app.use(
  // Put Auth0 to the first place to override other plugins
  createAuth0({
    domain: EnvConfig.authDomain,
    client_id: EnvConfig.authClientId,
    redirect_uri: window.location.origin,
    audience: EnvConfig.authMpApiAudience, 
  })
);
```


**router.ts**
```
import { authGuard } from "@auth0/auth0-vue";

  {
    path: "/:id?",
    name: "Home",
    component: Home,
    beforeEnter: authGuard,
    meta: {
      breadcrumb: t("sideBar.home"), 
    },
  },
```

**component.vue**
```
import { useAuth0 } from "@auth0/auth0-vue";
const { logout, user, isAuthenticated } = useAuth0();

const logoutUser = () => {
  logout({
    returnTo: window.location.origin + import.meta.env.BASE_URL,
  });
  //push({ path: window.location.origin + import.meta.env.BASE_URL });
};
```

**outsideComponent.ts** (NOT WORKING YET - error) 
```
import { useAuth0 } from "@auth0/auth0-vue";

async function getToken() {
    const { getAccessTokenSilently } = useAuth0(); // !!!! TypeError: Cannot destructure property 'getAccessTokenSilently' of 'useAuth0(...)' as it is undefined.
    const accessTokenData = await getAccessTokenSilently(options);

  // do something
  }
```

**Comment by frederikprijck** [comment] 2022-04-20 07:05
@onurusluca this is not using the[ workaround mentioned above](https://github.com/auth0/auth0-vue/issues/99#issuecomment-1102447205).

You need to use what is mentioned there (So add the new plugin yourself, register it using `app.use()` and import the correct thing in your `outsideComponent.ts`.

> Does this use aut0-vue or spa-js? Or do we have to use both?

This uses `auth0-vue`.

**Comment by onurusluca** [comment] 2022-04-21 02:18
@frederikprijck 
Tried to implement that but got some type errors and tried to fix. Let me know if I am doing something wrong.
After this is fixed, we really need this in documentation with examples. 


**exposeAuth.ts:**

```
import { Auth0VueClient } from "@auth0/auth0-vue";
import { Ref } from "vue";

export const client: Ref<Auth0VueClient> = ref(null); // Client type error: Ref<null> is not assignable to Ref<Auth0VueClient>

export function exposeAuth0() {
  return {
    install(app: {
      config: { globalProperties: { [x: string]: Auth0VueClient } };
    }) {
      client.value = app.config.globalProperties["$auth0"];
    },
  };
}
```

**main.ts:**

`app.use(exposeAuth0);`


**outsideComponent.ts:**

```
import { client } from "@/auth/exposeAuth";

export async function getAccessTokenSilentlyOutsideComponent(
  options: GetTokenSilentlyOptions
) {
  return unref(client).getAccessTokenSilently(options);
}

async function getToken() {

  const accessTokenData = await getAccessTokenSilentlyOutsideComponent(options);
  return {
    access_token: accessTokenData,
  };
}
```

Gives me: 
> TypeError: Cannot read properties of null (reading 'getAccessTokenSilently')
>     at getAccessTokenSilentlyOutsideComponent

**Comment by frederikprijck** [comment] 2022-04-21 05:19
@onurusluca  Please read [the workaround I mentioned](https://github.com/auth0/auth0-vue/issues/99#issuecomment-1102447205) more carefully. You are not implementing what is being mentioned. What you are doing is not how you register plugins with Vue. You should use `app.use(exposeAuth0())` instead of `app.use(exposeAuth0)`.

> After this is fixed, we really need this in documentation with examples.

This is nothing but a temporary workaround. No plans to document this.

**Comment by onurusluca** [comment] 2022-04-21 05:23
@frederikprijck Thanks for the reply. Forgot the "()". It is working now.
What about the types? Do we have to import the spa-js for types?

> This is nothing but a temporary workaround. No plans to document this.
I meant, we should write a documentation after finding a better way for using auth0 outside of component.

**Comment by frederikprijck** [comment] 2022-04-21 05:24
If some type isnt available in our Vue SDK, please open another issue. If that would be the case, you should be able to import the types from spa-js yes.

**Comment by frederikprijck** [comment] 2022-04-21 05:30
@set321go:

> I'm relatively new to vue but I think something thats missing from the documentation is some examples using vuex/pinia, with my limited knowledge I would take what has been talked about here (looking for how to integrate with a store is what got me here in the first place) and somehow shoehorn that into my store but that might be completely the wrong approach.

> it might be some minor changes to the login/logout/profile examples are all that are needed to do it 'properly' I think most people are just after that 'store the profile and login state' use case.

Our SDK focusses on the snippets needed to use our SDK, and not on how you want to use it. It's not on us to tell you how you should integrate things with any state management library of choice.

> with my limited knowledge I would take what has been talked about here

I don't think our examples exist to cover for that limited knowledge. I understand the problem, but educating yourself more deeply in Vuex/Pina is probably a better idea if you believe your knowledge about it is limited.

**Comment by frederikprijck** [comment] 2022-05-03 07:45
I cut [a new release (1.0.1)](https://github.com/auth0/auth0-vue/releases/tag/v1.0.1) that allows using [the approach mentioned above](https://github.com/auth0/auth0-vue/issues/99#issuecomment-1099704276).

That should solve most use cases discussed in this thread. Closing this for now.

**Closed by frederikprijck** 2022-05-03 07:45 UTC
Labels: needs investigation, feature request

**Comment by jdalrymple** [comment] 2022-08-05 14:12
@frederikprijck Following up on that release. Is it possible to access the property "isAuthenticated" ? When i attempt to access it, i just receive a proxy variable

**Comment by frederikprijck** [comment] 2022-08-05 14:18
Can you open another issue and provide an example of what you are doing that's not behaving as expected?

**Comment by rristoferbowers** [comment] 2023-03-23 08:24
> I added a draft PR that makes a change to the SDK that I believe should allow the usage of this SDK outside of a component.
> 
> In essence, I [reworked the internal structure of the plugin](https://github.com/auth0/auth0-vue/commit/8f22698e33a8cc525878b92a9c9ea6914db2f8ea) to allow the creation of the plugin to be moved to an external file:
> 
> ```ts
> export const auth0 = createAuth0({ ... });
> ```
> 
> Next, you can import the exported plugin instance when configuring the Vue app.
> 
> ```ts
> import { auth0 } from './auth0';
> 
> createApp(App)
>   .use(auth0)
>   .mount('#app');
> ```
> 
> However, you can now also import the exported plugin instance anywhere else and access it's methods
> 
> ```ts
> import { auth0 } from './auth0'
> 
> export async function getAccessTokenSilentlyOutsideComponent(options) {
>   return auth0.getAccessTokenSilently(options);
> }
> ```
> 
> Even though this pattern was already possible before, previously we didn't expose the SDK's methods on the object returned by `createAuth0`. However, looking at popular plugins (see [Vuex](https://github.com/vuejs/vuex/blob/main/src/store.js) and [Vue-Router](https://github.com/vuejs/router/blob/main/src/router.ts)). it appears to be common practice to keep the methods on the same instance that is used to pass to `app.use()`, allowing to use the SDK outside of a component using a structure mentioned above.
> 
> Here is a link showing how you can use the SDK with the changes: [1590a84](https://github.com/auth0/auth0-vue/commit/1590a84842d63a2c0003feb62fe6f9d8661285bd)
> 
> Would this work for your situation @Soviut @BrentonCozby @frankkoornstra @Cmacu?

Please mark it as solution
